"""add order_number

Revision ID: 70dda03bdc6f
Revises: e1a7ac93b7a1
Create Date: 2026-03-03 19:18:58.171909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dda03bdc6f'
down_revision: Union[str, Sequence[str], None] = 'e1a7ac93b7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.String(length=10), nullable=False))
    op.create_unique_constraint(None, 'orders', ['order_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
